freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  env:
    matrix:
      - LISP: sbcl
      - LISP: ccl
  preinstall_script:
    - pkg install -y curl git
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
    - cl -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
    - git clone --depth=1 git://github.com/shamazmazum/codex.git ~/lisp/codex
    - git clone --depth=1 git://github.com/shamazmazum/docparser.git ~/lisp/docparser
  script:
    - cl -f $CIRRUS_WORKING_DIR/tests/travis.lisp
    # - cl -l codex -e '(codex:document :wavelet-audio :skip-undocumented t)'
