dist: bionic
language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl -l easy-audio -l fiveam -l flexi-streams -e '(ql-util:without-prompting (ql:add-to-init-file))'

before-script:
  - mkdir lisp && pushd lisp && git clone git://github.com/shamazmazum/trivial-bit-streams.git && popd

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp
