name: Documentation

on:
  push:
    tags: [v*]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      LISP: sbcl-bin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Build documentation
        run: |
          cd $GITHUB_WORKSPACE
          qlot install
          qlot exec ros -s codex -e '(codex:document :wavelet-audio :skip-undocumented t)'
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/wavelet-audio/html
